work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN

# As a Sample
# CROSS-SUB x-sub

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D/occlude/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/occlude/xsub/train_label.pkl
test_feeder_args:
  data_path: ./data/NTU-RGB-D/occlude/xsub/val_data.npy
  label_path: ./data/NTU-RGB-D/occlude/xsub/val_label.pkl
complete_skeleton_args:
  data_path: ./data/NTU-RGB-D/complete/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/complete/xsub/train_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
# device: [0,1,2,3]
device: [0]
# batch_size: 64
batch_size: 1
# test_batch_size: 64
test_batch_size: 1
# num_epoch: 80
num_epoch: 2



